
server:
  #端口
  port: 8763
  #项目名称
  context-path: /message
  
#客户端注册到eureka服务列表内  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
    #对外暴露的微服务名字
  application:
    name: message
  #activemq的配置 
  activemq:
    #activemq的地址
    broker-url: tcp://localhost:61616
    # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    in-memory: true
    pool:
    #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      enabled: false  
  #邮件的配置文件    
  mail:
    #设置邮箱主机
    host: smtp.163.com
    #用户名
    username: yushengjun20180315@163.com
    #密码
    password: itmayiedu123456
    #设置是否需要认证，如果为true,那么用户名和密码就必须的，
    enable:  true
    #如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
    smtp:
      auth: true
   # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
    starttls:
      enable: true
      required: true
 
########################################

#自定义的配置文件
msg: 
  #标题
  subject: 蚂蚁课堂|每特教育提示您，会员注册成功邮件。
  #内容
  text:  恭喜您的账户{},注册成功!蚂蚁课堂|每特教育 上海每特教育科技有限公司 www.itmayiedu.com
