server:
  port: 8762
    
spring:
   application:                                             # 对外暴露的微服务名字
    name: member
  #mysql配置文件
  ##数据库连接信息
   datasource:  
    url: jdbc:mysql://localhost:3306/jbg_member?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    ###############以上为配置druid添加的配置########################################
   redis:
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1    
   ##activemq连接信息
   activemq:
     broker-url: tcp://localhost:61616
     in-memory: true
     pool:
       enabled: false   
#定义消息队列
messages:
   queue: messages_queue       
       

#mybatis配置文件
mybatis:
    #扫描实体类
     type-aliases-package: com.jbg.entity
    #扫描mybatis文件
     mapper-locations: classpath:mybatis/*.xml
#开启控制台打印sql语句，一般用于本地开发测试
#     configuration:
#             log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:     

eureka:
    #客户端注册到eureka服务列表内
    client: 
      service-url:
          defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
  file: jbg_mall.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

